const OPEN_MODAL = "OPEN_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";

const OPEN_CTA_MODAL = "OPEN_CTA_MODAL";
const CLOSE_CTA_MODAL = "CLOSE_CTA_MODAL";

const OPEN_EDIT_MODAL = "OPEN_EDIT_MODAL";
const CLOSE_EDIT_MODAL = "CLOSE_EDIT_MODAL";

const OPEN_TABLE_MODAL = "OPEN_TABLE_MODAL";
const CLOSE_TABLE_MODAL = "CLOSE_TABLE_MODAL";

const OPEN_DELETE_MODAL = "OPEN_DELETE_MODAL";
const CLOSE_DELETE_MODAL = "CLOSE_DELETE_MODAL";

const OPEN_SECTION_MODAL = "OPEN_SECTION_MODAL";
const CLOSE_SECTION_MODAL = "CLOSE_SECTION_MODAL";

const OPEN_EDIT_TABLE_MODAL = "OPEN_EDIT_TABLE_MODAL";
const CLOSE_EDIT_TABLE_MODAL = "CLOSE_EDIT_TABLE_MODAL";

const OPEN_SECTION_HEADER_MODAL = "OPEN_SECTION_HEADER_MODAL";
const CLOSE_SECTION_HEADER_MODAL = "CLOSE_SECTION_HEADER_MODAL";

const OPEN_SECTION_MAIN_SECTION_MODAL = "OPEN_SECTION_MAIN_SECTION_MODAL";
const CLOSE_SECTION_MAIN_SECTION_MODAL = "CLOSE_SECTION_MAIN_SECTION_MODAL";

export {
  OPEN_MODAL,
  CLOSE_MODAL,
  OPEN_EDIT_MODAL,
  CLOSE_EDIT_MODAL,
  OPEN_SECTION_MODAL,
  CLOSE_SECTION_MODAL,
  OPEN_SECTION_HEADER_MODAL,
  CLOSE_SECTION_HEADER_MODAL,
  OPEN_SECTION_MAIN_SECTION_MODAL,
  CLOSE_SECTION_MAIN_SECTION_MODAL,
  OPEN_TABLE_MODAL,
  CLOSE_TABLE_MODAL,
  OPEN_EDIT_TABLE_MODAL,
  CLOSE_EDIT_TABLE_MODAL,
  OPEN_DELETE_MODAL,
  CLOSE_DELETE_MODAL,
  OPEN_CTA_MODAL,
  CLOSE_CTA_MODAL,
};
